name: HuskHomesMenu
main: win.obydux.huskhomes.menu.HuskHomesMenu
version: '${version}'
description: 'Display HuskHomes homes and warps in a GUI'
api-version: 1.20
depend: [ 'HuskHomes' ]
folia-supported: true
authors: ['William278', 'Obydux']
website: 'https://github.com/Obydux/HuskHomesMenu'

commands:
  huskhomesmenu:
    description: 'View HuskHomesMenu plugin information & reload configs'
    usage: '/<command> <reload/about>'
    permission: 'huskhomesmenu.command'

permissions:
  huskhomesmenu.command:
    description: 'Allows access to the /huskhomesmenu command'
    default: op